# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\programming\BioTx\MVC\view\_qt\MainWindow.ui'
#
# Created: Tue Mar 01 14:56:33 2011
#      by: PyQt4 UI code generator 4.5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.timeButton = QtGui.QPushButton(self.centralwidget)
        self.timeButton.setObjectName("timeButton")
        self.horizontalLayout.addWidget(self.timeButton)
        self.downloadButton = QtGui.QPushButton(self.centralwidget)
        self.downloadButton.setObjectName("downloadButton")
        self.horizontalLayout.addWidget(self.downloadButton)
        self.uploadButton = QtGui.QPushButton(self.centralwidget)
        self.uploadButton.setObjectName("uploadButton")
        self.horizontalLayout.addWidget(self.uploadButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tableView = Spreadsheet(self.centralwidget)
        self.tableView.setObjectName("tableView")
        self.verticalLayout.addWidget(self.tableView)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.txTextBrowser = QtGui.QTextBrowser(self.centralwidget)
        self.txTextBrowser.setMaximumSize(QtCore.QSize(16777215, 100))
        self.txTextBrowser.setObjectName("txTextBrowser")
        self.horizontalLayout_2.addWidget(self.txTextBrowser)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.rxTextBrowser = QtGui.QTextBrowser(self.centralwidget)
        self.rxTextBrowser.setMaximumSize(QtCore.QSize(16777215, 100))
        self.rxTextBrowser.setObjectName("rxTextBrowser")
        self.horizontalLayout_3.addWidget(self.rxTextBrowser)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 19))
        self.menubar.setObjectName("menubar")
        self.menuSoubor = QtGui.QMenu(self.menubar)
        self.menuSoubor.setObjectName("menuSoubor")
        self.menuBIOTX = QtGui.QMenu(self.menubar)
        self.menuBIOTX.setObjectName("menuBIOTX")
        self.menuNastaveni = QtGui.QMenu(self.menubar)
        self.menuNastaveni.setObjectName("menuNastaveni")
        self.menuN_pov_da = QtGui.QMenu(self.menubar)
        self.menuN_pov_da.setObjectName("menuN_pov_da")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNov = QtGui.QAction(MainWindow)
        self.actionNov.setObjectName("actionNov")
        self.actionOtev_t = QtGui.QAction(MainWindow)
        self.actionOtev_t.setObjectName("actionOtev_t")
        self.actionUlo_it = QtGui.QAction(MainWindow)
        self.actionUlo_it.setObjectName("actionUlo_it")
        self.actionUlo_it_jako = QtGui.QAction(MainWindow)
        self.actionUlo_it_jako.setObjectName("actionUlo_it_jako")
        self.actionDownload_data = QtGui.QAction(MainWindow)
        self.actionDownload_data.setObjectName("actionDownload_data")
        self.actionUpload_data = QtGui.QAction(MainWindow)
        self.actionUpload_data.setObjectName("actionUpload_data")
        self.actionNastavit_hodiny = QtGui.QAction(MainWindow)
        self.actionNastavit_hodiny.setObjectName("actionNastavit_hodiny")
        self.actionZm_na_S_N = QtGui.QAction(MainWindow)
        self.actionZm_na_S_N.setObjectName("actionZm_na_S_N")
        self.actionNastaven_korekce = QtGui.QAction(MainWindow)
        self.actionNastaven_korekce.setObjectName("actionNastaven_korekce")
        self.actionCOM_Port = QtGui.QAction(MainWindow)
        self.actionCOM_Port.setObjectName("actionCOM_Port")
        self.actionHelo = QtGui.QAction(MainWindow)
        self.actionHelo.setObjectName("actionHelo")
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuSoubor.addAction(self.actionNov)
        self.menuSoubor.addAction(self.actionOtev_t)
        self.menuSoubor.addAction(self.actionUlo_it)
        self.menuSoubor.addAction(self.actionUlo_it_jako)
        self.menuBIOTX.addAction(self.actionDownload_data)
        self.menuBIOTX.addAction(self.actionUpload_data)
        self.menuBIOTX.addAction(self.actionNastavit_hodiny)
        self.menuBIOTX.addAction(self.actionZm_na_S_N)
        self.menuBIOTX.addAction(self.actionNastaven_korekce)
        self.menuNastaveni.addAction(self.actionCOM_Port)
        self.menuN_pov_da.addAction(self.actionHelo)
        self.menuN_pov_da.addAction(self.actionAbout)
        self.menubar.addAction(self.menuSoubor.menuAction())
        self.menubar.addAction(self.menuBIOTX.menuAction())
        self.menubar.addAction(self.menuNastaveni.menuAction())
        self.menubar.addAction(self.menuN_pov_da.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "BioTx", None, QtGui.QApplication.UnicodeUTF8))
        self.timeButton.setText(QtGui.QApplication.translate("MainWindow", "Current Time", None, QtGui.QApplication.UnicodeUTF8))
        self.downloadButton.setText(QtGui.QApplication.translate("MainWindow", "Download", None, QtGui.QApplication.UnicodeUTF8))
        self.uploadButton.setText(QtGui.QApplication.translate("MainWindow", "Upload", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Tx", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Rx", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSoubor.setTitle(QtGui.QApplication.translate("MainWindow", "Soubor", None, QtGui.QApplication.UnicodeUTF8))
        self.menuBIOTX.setTitle(QtGui.QApplication.translate("MainWindow", "BIOTX", None, QtGui.QApplication.UnicodeUTF8))
        self.menuNastaveni.setTitle(QtGui.QApplication.translate("MainWindow", "Nastavení", None, QtGui.QApplication.UnicodeUTF8))
        self.menuN_pov_da.setTitle(QtGui.QApplication.translate("MainWindow", "Nápověda", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNov.setText(QtGui.QApplication.translate("MainWindow", "Nový", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOtev_t.setText(QtGui.QApplication.translate("MainWindow", "Otevřít", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUlo_it.setText(QtGui.QApplication.translate("MainWindow", "Uložit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUlo_it_jako.setText(QtGui.QApplication.translate("MainWindow", "Uložit jako", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDownload_data.setText(QtGui.QApplication.translate("MainWindow", "Download data", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUpload_data.setText(QtGui.QApplication.translate("MainWindow", "Upload data", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNastavit_hodiny.setText(QtGui.QApplication.translate("MainWindow", "Nastavit hodiny", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZm_na_S_N.setText(QtGui.QApplication.translate("MainWindow", "Změna S/N", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNastaven_korekce.setText(QtGui.QApplication.translate("MainWindow", "Nastavení korekce", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCOM_Port.setText(QtGui.QApplication.translate("MainWindow", "COM Port", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelo.setText(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))

from spreadsheet import Spreadsheet
